"""lpi_latex.py -- the paper's metric tables, generated from an eval report.

Why: a table somebody retyped from a terminal is a table that quietly drifts away
from the run that produced it.  ``lpi_eval.py --latex run/eval.tex`` writes the two
IEEE-shaped tables straight out of the same JSON, so the manuscript and the
measurement cannot disagree -- and the per-SNR table carries the one-sided 95 %
Clopper-Pearson bound next to every point estimate, because "0 errors in 96 texts"
is a *bound* on the rate, not a rate.

No LaTeX packages are assumed (``\\hline``, not booktabs), and the pass column says
``yes``/``no`` rather than ``\\checkmark`` so the fragment compiles in any template.
"""
from __future__ import annotations

#: (report key, printed metric, target as printed, predicate, number format)
STEALTH_ROWS = [
    ("ks_p",     "KS $p$ (IQ vs. AWGN)",       "$>$ 0.05",     lambda v: v > 0.05,          "%.4f"),
    ("kurt",     "Kurtosis",                   "$3.0\\pm0.1$", lambda v: abs(v - 3.0) < 0.1, "%.3f"),
    ("entropy",  "Normalised entropy $H$",     "$>$ 0.95",     lambda v: v > 0.95,          "%.4f"),
    ("circ",     "Circularity",                "$<$ 0.15",     lambda v: v < 0.15,          "%.4f"),
    ("papr",     "PAPR deviation [dB]",        "$<$ 3",        lambda v: abs(v) < 3.0,      "%+.3f"),
    ("scf",      "SCF ratio",                  "$<$ 3",        lambda v: v < 3.0,           "%.3f"),
    ("c42",      "$C_{42}$",                   "$<$ 0.3",      lambda v: abs(v) < 0.3,      "%+.4f"),
    ("wvd",      "WVD TF ratio",               "$<$ 3.7",      lambda v: v < 3.7,           "%.3f"),
    ("Sc",       "Composite $Sc$",             "$<$ 0.20",     lambda v: v < 0.20,          "%.4f"),
]


def _row(cells):
    return " & ".join(str(c) for c in cells) + r" \\"


def latex_tables(rep, cfg, protocol: str = "", label_prefix: str = "lpi"):
    """Return a LaTeX fragment: Table (a) the statistical battery, Table (b) the
    link/message layer with 95 % upper bounds.

    ``rep`` is the dict ``lpi_eval.py`` writes with ``--out-json``; anything it does
    not carry (older runs, a hand-made dict) degrades to the point estimate rather
    than crashing, so this stays usable on yesterday's JSON.
    """
    st = rep["block_stealth"]
    ln = rep["block_link"]
    ms = rep.get("block_message", {})
    nb = int(sum(float(r.get("n_bits_tested", 0) or 0) for r in ln.values()))
    nt = int(sum(float(r.get("n", 0) or 0) for r in ms.values()))
    # per-point sizes, because the bound is computed per point; totals are for scale
    npt = max(len(ln), 1)
    bpp, tpp = (nb // npt), (nt // len(ms) if ms else 0)
    L = [f"% generated by lpi_v4/lpi_eval.py --latex from this run; do not hand-edit"]
    if protocol:
        L.append("% protocol: " + protocol.replace("%", r"\%"))
    L += ["",
          r"\begin{table}[t]", r"\centering",
          f"\\caption{{Statistical LPI battery of the generated waveform "
          f"(T={cfg.frame_len} samples, {cfg.n_bits} bits per frame, "
          f"{cfg.pilot_len}-sample keyed preamble).}}",
          f"\\label{{tab:{label_prefix}-stealth}}",
          r"\begin{tabular}{@{}lccc@{}}", r"\hline",
          _row(["Metric", "Target", "Measured", "Pass"]), r"\hline"]
    for key, name, target, ok, fmt in STEALTH_ROWS:
        v = float(st[key])
        L.append(_row([name, target, fmt % v, "yes" if ok(v) else "no"]))
    adv = float(st.get("fit_adv_acc", st.get("adv_acc", 50.0)))
    auc = float(st.get("fit_adv_auc", st.get("adv_auc", 0.5)))
    L.append(_row([r"Adversary accuracy [\%] (held out)", "48--56", f"{adv:.2f}",
                   "yes" if 48.0 <= adv <= 56.0 else "no"]))
    L.append(_row(["Adversary AUC", "---", f"{auc:.4f}",
                   "yes" if max(auc, 1.0 - auc) < 0.65 else "no"]))
    L.append(_row(["Domains passed", "8/8", f"{int(st['n_pass'])}/8",
                   "yes" if int(st["n_pass"]) >= 8 else "no"]))
    L += [r"\hline", r"\end{tabular}", r"\end{table}", "",
          r"\begin{table}[t]", r"\centering",
          r"\caption{Bit- and frame-error rates through the field path (keyed sync, "
          r"CFO, phase noise, DC, IQ imbalance). The 95\,\% column is the one-sided "
          r"Clopper--Pearson upper bound: what the sample actually supports. "
          + (f"{bpp:,} bits and {tpp} texts per SNR point ({nb:,} / {nt} over "
             f"{npt} swept points). " if (nb or nt) else "") + "}",
          f"\\label{{tab:{label_prefix}-link}}",
          r"\begin{tabular}{@{}lccccc@{}}", r"\hline",
          _row(["SNR [dB]", "MF", "In-graph", "Field", r"Field $\leq$ 95\,\%",
                r"FER [\%] $\leq$ 95\,\%"]), r"\hline"]
    for snr, r in ln.items():
        pt = float(r["field"])
        ub = float(r.get("field_ci95", pt))
        fer = 100.0 * float(r["fer"])
        fer_ub = 100.0 * float(r.get("fer_ci95", r["fer"]))
        L.append(_row([f"{float(snr):g}", f"{r['mf']:.2e}", f"{r['graph']:.2e}",
                       f"{pt:.2e}", f"{ub:.2e}", f"{fer:.2f} ({fer_ub:.1f})"]))
    L += [r"\hline", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L) + "\n"
